## NumPy Arrays

In [2]:
#Python List
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
#Converting Python List To Numpy Array
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [18]:
#Python Lists Of Lists
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
#Converting Python Lists Of Lists To Numpy Matrix
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
#Numpy Range Function To Generate Numbers In Given Range
np.arange(3,11)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#Numpy Range Function To Generate Numbers In Given Range With Equal Intervals
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
#Numpy Zeros Function Generates Numpy Array Of Zeros Of Given Length.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
#Numpy Ones Function Generates Numpy Array Of Ones Of Given Length.
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((4,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [19]:
#Numpy Linspace Generates Evenly Spaced Numbers Over A Specified Interval.
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [20]:
#Identity Matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
#Numpy Random Rand Returns Given Length Of Numbers From Uniform Distribution Of Zero And One
np.random.rand(5)

array([0.12349456, 0.37083794, 0.33064936, 0.93924638, 0.53731743])

In [22]:
np.random.rand(5,5)

array([[0.24011322, 0.66998303, 0.52065322, 0.70641935, 0.30253172],
       [0.59399744, 0.39134019, 0.29522078, 0.20691675, 0.32150255],
       [0.43202052, 0.59212166, 0.79497732, 0.10191601, 0.23292502],
       [0.61054905, 0.41350227, 0.33625984, 0.80457691, 0.85868318],
       [0.45968373, 0.57261103, 0.66438843, 0.09421182, 0.79391745]])

In [23]:
#Numpy Random Randn Returns Given Length Of Numbers From Normal Distribution Centered Around Zero
np.random.randn(3)

array([-0.59173992,  0.36868755,  0.76768626])

In [24]:
np.random.randn(5,5)

array([[ 0.4725043 ,  0.29871721, -0.14027968, -0.40095148,  0.2332238 ],
       [-1.38157506,  0.8418577 ,  1.4501532 , -1.24868129,  1.14546327],
       [ 1.18076132, -0.97050017,  0.7243439 , -1.31146929, -1.22615686],
       [ 0.85781188, -0.1452985 ,  0.25602942,  0.95877309,  0.90257209],
       [ 2.56701799,  1.25896973, -0.79583697,  0.89808874,  0.54940256]])

In [29]:
#Numpy Random Randnt Returns A Interger From Specified Range.
np.random.randint(1,100)

30

In [30]:
np.random.randint(1,101,10)

array([ 76,  28,   7,  40,  19,  43,  33,   9,  95, 100])

In [32]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr = np.random.randint(0,50,10)
ranarr

array([32,  8, 16, 11, 25, 16,  4,  9, 30, 41])

In [38]:
#Numpy Reshape Fn Reshapes The Array To Given Dimensions
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
#If Total Number Of Elements Are Not Same In Both The Arrays, A Error Will Be Thrown.
arr.reshape(5,10)

ValueError: cannot reshape array of size 25 into shape (5,10)

In [40]:
#Fn To Return Max Element In NP Array
ranarr.max()

41

In [41]:
#Fn To Return Min Element In NP Array
ranarr.min()

4

In [42]:
#Fn To Return Pos Of Max Element In NP Array
ranarr.argmax()

9

In [43]:
#Fn To Return Pos Of Min Element In NP Array
ranarr.argmin()

6

In [44]:
#An Attribute That Returns Shape Of The Array
arr.shape

(25,)

In [45]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [46]:
#An Attribute That Returns Data type Of Given Np Array
arr.dtype

dtype('int32')