## Numpy Indexing And Seletion

In [2]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8]

8

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [7]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0,11)
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [12]:
arr_copy = arr.copy()
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [13]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
arr_2d[0]

array([ 5, 10, 15])

In [19]:
arr_2d[0][0]

5

In [20]:
arr_2d[1][1]

25

In [21]:
arr_2d[0,0]

5

In [22]:
arr_2d[1,1]

25

In [26]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [28]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [29]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [30]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
bool_array = arr > 5
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [33]:
arr[bool_array]

array([ 6,  7,  8,  9, 10])

In [34]:
arr[arr < 3]

array([1, 2])

In [36]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])